#!/bin/bash
#
# Copyright (c) 2016, Cormac Flanagan (University of California, Santa Cruz)
#                     and Stephen Freund (Williams College) 
#
# All rights reserved.  
# 
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are
# met:
# 
#    * Redistributions of source code must retain the above copyright
#      notice, this list of conditions and the following disclaimer.
#
#    * Redistributions in binary form must reproduce the above
#      copyright notice, this list of conditions and the following
#      disclaimer in the documentation and/or other materials provided
#      with the distribution.
#
#    * Neither the names of the University of California, Santa Cruz
#      and Williams College nor the names of its contributors may be
#      used to endorse or promote products derived from this software
#      without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
# "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
# LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
# A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
# HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
# SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
# LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
# DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
# THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
# (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
# OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
#

TARGET="dacapo.hsqldb.Main"
PROGRAM_ARGS=""
NUM_ITER=500

rm -rf rr_runs
mkdir rr_runs
for i in `seq 1 $NUM_ITER`
do
   PROGRAM_ARGS="small"
   rrrun -classpath=data:../../shared/dacapo-2006-10-MR2/classes:classes:jar/hsqldb.jar -infThreads=1000 -maxTid=128 -stacks -tool=FT_LOC ${TEST_ARGS} $* ${TARGET} ${PROGRAM_ARGS} > rr_runs/rr_out_1_$i 2>&1

   PROGRAM_ARGS="default"
   rrrun -classpath=data:../../shared/dacapo-2006-10-MR2/classes:classes:jar/hsqldb.jar -infThreads=1000 -maxTid=128 -stacks -tool=FT_LOC ${TEST_ARGS} $* ${TARGET} ${PROGRAM_ARGS} > rr_runs/rr_out_2_$i 2>&1

   PROGRAM_ARGS="large"
   rrrun -classpath=data:../../shared/dacapo-2006-10-MR2/classes:classes:jar/hsqldb.jar -infThreads=1000 -maxTid=128 -stacks -tool=FT_LOC ${TEST_ARGS} $* ${TARGET} ${PROGRAM_ARGS} > rr_runs/rr_out_3_$i 2>&1
done
